spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: false

server:
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    com.forestock.forestock_backend: INFO
    org.springframework.security: WARN
    root: WARN

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
